def format_symbol(raw_input):
    symbol = raw_input.strip().upper()  # Remove spaces and convert to uppercase
    if not symbol.endswith(".NS"):
        symbol += ".NS"
    return symbol




symbols = ['HIMATSEIDE.NS' ,'BOMDYEING.NS', 'THOMASCOOK.NS', 'JWL.NS', 'BALAJITELE.NS', 'SPANDANA.NS', 'KCP.NS', 'RAJESHEXPO.NS', 'BLS.NS', 'BANSWRAS.NS', 'DHAMPURSUG.NS', 'CMSINFO.NS', 'INDIANHUME.NS', 'DWAREKESH.NS', 'GNA.NS', 'RSWM.NS', 'KPEL.NS', 'TI.NS', 'PRSMJOHNSN.NS', 'BPCL.NS', 'LAOPALA.NS', 'NCC.NS', 'HINDPETRO.NS', 'GICHSGFIN.NS', 'TARC.NS', 'NDTV.NS', 'SKYGOLD.NS', 'BHEL.NS', 'DEEDEV.NS', 'DALMIASUG.NS', 'REMSONSIND.NS', 'SMSPHARMA.NS', 'TDPOWERSYS.NS', 'LTFOODS.NS', 'CANBK.NS', 'NRL.NS', 'IDBI.NS', 'KHAICHEM.NS', 'PNCINFRA.NS', 'CARRARO.NS', 'ASHOKA.NS', 'STARHEALTH.NS', 'BHAGERIA.NS', 'SURYAROSNI.NS', 'VLEGOV.NS', 'TOLINS.NS', 'NIACL.NS', 'BSOFT.NS', 'SBFC.NS', 'DELTAMAGNT.NS', 'SUVEN.NS', 'WCIL.NS', 'KELLTONTEC.NS', 'ENGINEERSIN.NS', 'RAILTEL.NS', 'TALBROAUTO.NS', 'HEMIPROP.NS', 'IGL.NS', 'MVGJL.NS', 'ACMESOLAR.NS', 'MAMATA.NS', 'SURAKSHA.NS', 'GREENLAM.NS', 'CSBBANK.NS', 'MANCREDIT.NS', 'NTPCGREEN.NS', 'GENUSPOWER.NS', 'DIACABS.NS', 'JGCHEM.NS', 'FILATEX.NS', 'APTECHT.NS', 'SHANTIGEAR.NS', 'EPL.NS', 'RUPA.NS', 'JAICORPLTD.NS', 'SUZLON.NS', 'MANGCHEFER.NS', 'MEGASOFT.NS', 'HINDCOPPER.NS', 'SMCGLOBAL.NS', 'GODIGIT.NS', 'CAMLINFINE.NS', 'UNIONBANK.NS', 'SENCO.NS', 'BEL.NS', 'SCI.NS', 'ZEEL.NS', 'MCLOUD.NS', 'ROTO.NS', 'PENIND.NS', 'KRBL.NS', 'IRCON.NS', '5PAISA.NS', 'RKEC.NS', 'KOTHARIPRO.NS', 'VINCOFE.NS', 'BODALCHEM.NS', 'MUKANDLTD.NS', 'SATIA.NS', 'SNOWMAN.NS'


]
formatted_symbols = [format_symbol(s) for s in symbols]
print(formatted_symbols)